---
title: "PCA for metallic glass prediction"
author: "Rongrong Dai"
date: "April 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Load the data and library

```{r }
library(ggplot2)

data = read.table("gfa_data_2.csv", header = TRUE, sep = ",")
GfaPredictor = data[, -ncol(data)]

rep.row<-function(x,n){
  matrix(rep(x,each=n),nrow=n)
}
```

## Create centralized data

```{r }
GfaPredictor_cent = GfaPredictor - rep.row(apply(GfaPredictor, 2, mean),nrow(GfaPredictor))
dev = sqrt(apply(GfaPredictor, 2, var))
GfaPredictor_cent_scaled = as.matrix(t(apply(GfaPredictor_cent, 1, function(x) x/dev)))
```

## Implement principle component analysis
```{r}
cov_gfa_centra = 1/((nrow(GfaPredictor_cent_scaled))-1) * t(GfaPredictor_cent_scaled) %*% GfaPredictor_cent_scaled
results = eigen(cov_gfa_centra)
pca_eigen_value = results$values
sum_information = sum(results$values)
accumulative = 0
for (i in 1:length(results$values)){
  accumulative = accumulative + results$values[i]
  accu_write = paste(i,"\t",accumulative/sum_information)
  write(accu_write,"accumulate_information.txt", append = TRUE)
}

accumulative_information <- read.delim("accumulate_information.txt", header = FALSE)
names(accumulative_information) <- c("number_of_principle_components", "accumulative_information")

ggplot(accumulative_information, aes(x = number_of_principle_components, y = accumulative_information )) + geom_point()
```

## 3D plot of the new data using top 3 priciple components

```{r, message=FALSE}
top_3_eigv <- results$vectors[, 1:3]
top_3_coord <- as.matrix(GfaPredictor_cent_scaled) %*% top_3_eigv
color_code <- rep("red", nrow(top_3_coord))

# Change glass former to "green"
color_code[grep("1", data$Class)] = "green"

# 3D plot using top 3 priciple components

car::scatter3d(x = top_3_coord[, 1], y = top_3_coord[, 2], z = top_3_coord[, 3],
               point.col = color_code,sphere.size=3,
               grid = FALSE, surface = FALSE)
```

## 2D plot using top 2 priciple components

```{r}
top_2_coord <- as.matrix(GfaPredictor_cent_scaled) %*% results$vectors[, 1:2]
plot(x = top_2_coord[, 1], y = top_2_coord[, 2], col = color_code, xlab="First principle component", ylab="Second principle component",
  xlim=c(-13, 20), ylim=c(-13, 20))
legend("topleft", inset=.02, legend=c("Glass former", "Non glass former"),
       fill = c("red", "green"), horiz = TRUE, cex=0.8)

```

